PYTHON ?= python3
PIP ?= pip
VENV ?= .venv

.PHONY: all install generate update-version help clean-venv docs-serve docs-build

help:
	@echo "Available commands:"
	@echo "  make install         - Create Python 3.11+ venv and install dependencies"
	@echo "  make generate        - Regenerate Python and TypeScript bindings"
	@echo "  make update-version  - Propagate version from VERSION file to all files AND regenerate bindings"
	@echo "  make docs-serve      - Run the MkDocs dev server for the docs/"
	@echo "  make docs-build      - Build the MkDocs site to docs/site/"
	@echo "  make clean-venv      - Remove the existing virtual environment"

install:
	@# Ensure Python 3.11+ is available
	@if ! command -v python3.11 >/dev/null 2>&1; then \
		echo "Error: python3.11 is not installed or not in PATH."; \
		echo "Please install Python 3.11 (e.g., via 'brew install python@3.11' on macOS)."; \
		exit 1; \
	fi
	@# Create venv if it doesn't exist
	@if [ ! -d "$(VENV)" ]; then \
		echo "Creating virtual environment using python3.11..."; \
		python3.11 -m venv $(VENV); \
	else \
		echo "Virtual environment already exists at $(VENV)"; \
	fi
	@# Install dependencies inside venv
	@echo "Installing dependencies..."
	@$(VENV)/bin/pip install --upgrade pip
	@$(VENV)/bin/pip install "datamodel-code-generator[http,black]==0.72.3"
	@echo "Installing MkDocs + Material theme + Mermaid..."
	@$(VENV)/bin/pip install mkdocs-material mkdocs-mermaid2-plugin
	@echo "Installing TypeScript dependencies..."
	cd bindings/typescript && npm install
	@echo "Installing code generation tools (dev only)..."
	npm install -g json-schema-to-typescript

clean-venv:
	rm -rf $(VENV)
	@echo "Virtual environment removed."

generate:
	@echo "⏳ Generating Python Pydantic Models..."
	@$(VENV)/bin/python -m datamodel_code_generator --input visualli.schema.json --input-file-type jsonschema --output bindings/python/visualli.py --output-model-type pydantic_v2.BaseModel --use-schema-description --field-constraints --use-annotated --use-union-operator --disable-timestamp
	@$(VENV)/bin/black bindings/python/visualli.py
	@sed -i.bak '/^# generated by datamodel-codegen:/d' bindings/python/visualli.py && rm bindings/python/visualli.py.bak
	@sed -i.bak '/^#   filename:  visualli.schema.json/d' bindings/python/visualli.py && rm bindings/python/visualli.py.bak
	@echo "✅ Python models generated at bindings/python/visualli.py"
	@echo "⏳ Generating TypeScript Interfaces..."
	@json2ts visualli.schema.json bindings/typescript/src/types.ts
	@echo "✅ TypeScript interfaces generated at bindings/typescript/src/types.ts"

update-version:
	@$(VENV)/bin/python scripts/update_version.py
	@echo "Regenerating bindings to reflect new version..."
	@$(MAKE) generate

docs-serve:
	@cd docs && ../$(VENV)/bin/mkdocs serve -f mkdocs.yml

docs-build:
	@cd docs && ../$(VENV)/bin/mkdocs build -f mkdocs.yml