# generated by datamodel-codegen:
#   filename:  visualli.schema.json

from __future__ import annotations
from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['meta']
    version: Annotated[str, Field(description="Visualli spec version (e.g. '0.1')")]
    title: str
    created: AwareDatetime | None = None
    lastModified: AwareDatetime | None = None


class Extension(BaseModel):
    type: Literal['extension']
    id: Annotated[
        str,
        Field(
            description="Unique identifier for the extension (e.g., 'semantic-anchors')"
        ),
    ]
    config: Annotated[
        dict[str, Any] | None,
        Field(description='Configuration parameters for the extension'),
    ] = None
    data: Annotated[
        list[Any] | None, Field(description='Data payload for the extension')
    ] = None


class Position(BaseModel):
    x: float
    y: float


class Data(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    label: Annotated[str | None, Field(description='Label text for the node')] = None
    color: str | None = None


class Node(BaseModel):
    id: str
    position: Position
    data: Data


class Connection(BaseModel):
    id: str
    from_: Annotated[str, Field(alias='from', description='Source Node ID')]
    to: Annotated[str, Field(description='Target Node ID')]
    label: str | None = None


class Container(BaseModel):
    id: str
    label: str
    nodes: Annotated[
        list[str], Field(description='List of Node IDs contained in this group')
    ]


class Layer(BaseModel):
    type: Literal['layer']
    id: Annotated[str, Field(description='UUID of the layer')]
    level: Annotated[int, Field(description='Hierarchy level (0 is root)', ge=0)]
    parentLayerId: Annotated[
        str | None, Field(description='UUID of the parent layer')
    ] = None
    parentNodeId: Annotated[
        str | None,
        Field(
            description='UUID of the specific node in the parent layer this layer attaches to'
        ),
    ] = None
    description: str | None = None
    nodes: Annotated[list[Node] | None, Field(default_factory=list)]
    connections: Annotated[list[Connection] | None, Field(default_factory=list)]
    containers: Annotated[list[Container] | None, Field(default_factory=list)]


class VisualliSpec010(RootModel[Meta | Extension | Layer]):
    root: Annotated[
        Meta | Extension | Layer,
        Field(
            description='Schema for a single line in a .visualli (JSONL) file. Each line must be one of: Meta, Extension, or Layer.',
            discriminator='type',
            title='Visualli Spec 0.1.0',
        ),
    ]
