import React from 'react';
import { VisualliRenderer } from '@mysdk/react';

// Water Cycle — rich multi-layer .visualli document
// Layers: root → overview (5 nodes) → evaporation / condensation / precipitation / collection (4 nodes each)
// Each child layer uses containers (nested data format) and descriptive summaries.
const WATER_CYCLE_JSONL = [
  `{"type":"meta","version":"1.0","created":"2024-05-21T00:00:00Z","lastModified":"2026-07-11T00:00:00Z","title":"Water Cycle"}`,

  // Level 0 — root
  `{"type":"layer","id":"root","level":0,"description":"Water Cycle","nodes":[{"id":"n-root","position":{"x":0,"y":0},"data":{"label":"💧 Water Cycle","summary":"The continuous movement of water within Earth and its atmosphere, powered by solar energy and shaped by gravity. About 496,000 km³ of water cycles annually."}}],"connections":[],"containers":[]}`,

  // Level 1 — overview (5 nodes, 1 radial container)
  `{"type":"layer","id":"layer-overview","level":1,"description":"Overview","parentNodeId":"n-root","parentLayerId":"root","nodes":[{"id":"n-evap","position":{"x":0,"y":0},"data":{"label":"☀️ Evaporation","summary":"Solar energy heats surface water, converting it to invisible vapour. Oceans supply 86% of atmospheric moisture through this process."}},{"id":"n-cond","position":{"x":0,"y":0},"data":{"label":"☁️ Condensation","summary":"Rising water vapour cools and condenses around tiny particles, forming cloud droplets that become the visible clouds we see."}},{"id":"n-precip","position":{"x":0,"y":0},"data":{"label":"🌧 Precipitation","summary":"When cloud droplets merge and grow heavy enough, they fall as rain, snow, sleet or hail depending on atmospheric temperature."}},{"id":"n-collect","position":{"x":0,"y":0},"data":{"label":"🌊 Collection","summary":"Precipitation gathers in oceans, lakes, rivers and underground aquifers, completing the cycle and feeding back into evaporation."}},{"id":"n-transport","position":{"x":0,"y":0},"data":{"label":"🌬 Transport","summary":"Atmospheric circulation carries water vapour from tropical oceans to inland regions, distributing fresh water across the globe."}}],"connections":[{"id":"ov1","from":"n-evap","to":"n-cond","label":"rises as vapour"},{"id":"ov2","from":"n-cond","to":"n-precip","label":"falls"},{"id":"ov3","from":"n-precip","to":"n-collect","label":"collects"},{"id":"ov4","from":"n-collect","to":"n-evap","label":"evaporates"},{"id":"ov5","from":"n-transport","to":"n-cond","label":"carries vapour"}],"containers":[{"id":"ov-all","nodes":["n-evap","n-cond","n-precip","n-collect","n-transport"],"data":{"label":"Hydrological Cycle","formation":"radial"}}]}`,

  // Level 2 — Evaporation detail (4 nodes, 1 container)
  `{"type":"layer","id":"layer-evap","level":2,"description":"Evaporation","parentNodeId":"n-evap","parentLayerId":"layer-overview","nodes":[{"id":"n-solar","position":{"x":0,"y":0},"data":{"label":"☀️ Solar Radiation","summary":"The sun delivers ~342 W/m² to Earth's surface. About 23% goes directly toward evaporation, powering the entire water cycle."}},{"id":"n-surface","position":{"x":0,"y":0},"data":{"label":"💧 Surface Water","summary":"Oceans, lakes and wet soil are the main sources. The ocean alone evaporates roughly 434,000 km³ of water every year."}},{"id":"n-vapour","position":{"x":0,"y":0},"data":{"label":"💨 Water Vapour","summary":"Individual molecules escape the liquid surface when kinetic energy exceeds surface tension. Vapour is invisible and lighter than air."}},{"id":"n-latent","position":{"x":0,"y":0},"data":{"label":"🔥 Latent Heat","summary":"Evaporation absorbs ~2,260 J/g of latent heat from the surface, cooling it. This stored energy is released when condensation occurs in clouds."}}],"connections":[{"id":"ev1","from":"n-solar","to":"n-surface","label":"heats"},{"id":"ev2","from":"n-surface","to":"n-vapour","label":"releases"},{"id":"ev3","from":"n-vapour","to":"n-latent","label":"carries"}],"containers":[{"id":"ev-all","nodes":["n-solar","n-surface","n-vapour","n-latent"],"data":{"label":"Evaporation Process","formation":"radial"}}]}`,

  // Level 2 — Condensation detail (4 nodes, 1 container)
  `{"type":"layer","id":"layer-cond","level":2,"description":"Condensation","parentNodeId":"n-cond","parentLayerId":"layer-overview","nodes":[{"id":"n-adiabat","position":{"x":0,"y":0},"data":{"label":"🏔 Adiabatic Cooling","summary":"As moist air rises it expands and cools ~9.8°C per 1,000 m. Once it drops below the dew point, condensation begins."}},{"id":"n-nuclei","position":{"x":0,"y":0},"data":{"label":"🔬 Cloud Condensation Nuclei","summary":"Tiny particles — sea salt, dust, pollen, smoke — act as seeds. Without them, air could supersaturate to 400% without forming a single droplet."}},{"id":"n-micro","position":{"x":0,"y":0},"data":{"label":"🌢 Micro Droplets","summary":"Cloud droplets are 10–100 µm in diameter — far too small to fall. About one million droplets must combine to form a single raindrop."}},{"id":"n-cloudtype","position":{"x":0,"y":0},"data":{"label":"☁️ Cloud Types","summary":"Cumulus (convective), stratus (layered) and cirrus (ice crystals at altitude) each reflect different thermodynamic conditions in the atmosphere."}}],"connections":[{"id":"co1","from":"n-adiabat","to":"n-nuclei","label":"activates"},{"id":"co2","from":"n-nuclei","to":"n-micro","label":"seeds"},{"id":"co3","from":"n-micro","to":"n-cloudtype","label":"builds"}],"containers":[{"id":"co-all","nodes":["n-adiabat","n-nuclei","n-micro","n-cloudtype"],"data":{"label":"Condensation Process","formation":"radial"}}]}`,

  // Level 2 — Precipitation detail (4 nodes, 2 containers: liquid / frozen)
  `{"type":"layer","id":"layer-precip","level":2,"description":"Precipitation","parentNodeId":"n-precip","parentLayerId":"layer-overview","nodes":[{"id":"n-rain","position":{"x":0,"y":0},"data":{"label":"🌧 Rain","summary":"Liquid droplets larger than 0.5 mm. Forms by droplet coalescence in warm clouds, or by snowflakes melting as they fall through warmer air."}},{"id":"n-sleet","position":{"x":0,"y":0},"data":{"label":"🌦 Sleet","summary":"Raindrops that refreeze in a sub-zero surface layer, forming ice pellets. Common in winter when warm and cold air masses meet."}},{"id":"n-snow","position":{"x":0,"y":0},"data":{"label":"❄️ Snow","summary":"Ice crystals grow by deposition (vapour→solid) around nuclei when temperatures stay below 0°C from cloud to ground."}},{"id":"n-hail","position":{"x":0,"y":0},"data":{"label":"🌨 Hail","summary":"Layered ice balls 5–150 mm across. Each layer marks one pass through a thunderstorm's updraft and freezing zone."}}],"connections":[{"id":"pr1","from":"n-rain","to":"n-sleet","label":"can freeze to"},{"id":"pr2","from":"n-snow","to":"n-hail","label":"intensifies to"}],"containers":[{"id":"pr-liquid","nodes":["n-rain","n-sleet"],"data":{"label":"Liquid Forms","formation":"linear-horizontal"}},{"id":"pr-frozen","nodes":["n-snow","n-hail"],"data":{"label":"Frozen Forms","formation":"linear-horizontal"}}]}`,

  // Level 2 — Collection detail (4 nodes, 2 containers: surface / stored)
  `{"type":"layer","id":"layer-collect","level":2,"description":"Collection","parentNodeId":"n-collect","parentLayerId":"layer-overview","nodes":[{"id":"n-ocean","position":{"x":0,"y":0},"data":{"label":"🌊 Oceans","summary":"Cover 71% of Earth and hold 97.5% of all water. The ocean is the primary evaporation engine, cycling 434,000 km³ per year."}},{"id":"n-fresh","position":{"x":0,"y":0},"data":{"label":"🏞 Lakes & Rivers","summary":"Hold only 0.013% of Earth's water but are critical ecosystems and the primary human freshwater source for drinking and irrigation."}},{"id":"n-ground","position":{"x":0,"y":0},"data":{"label":"🪨 Groundwater","summary":"Fills pores in aquifer rock metres to hundreds of metres below the surface. Supplies ~30% of river flow via springs and base flow."}},{"id":"n-glacier","position":{"x":0,"y":0},"data":{"label":"🧊 Glaciers & Ice","summary":"Store ~69% of Earth's fresh water. Melting glaciers are raising sea levels ~3.6 mm per year, accelerating under climate change."}}],"connections":[{"id":"cl1","from":"n-ocean","to":"n-fresh","label":"feeds via rain"},{"id":"cl2","from":"n-fresh","to":"n-ground","label":"recharges"},{"id":"cl3","from":"n-glacier","to":"n-fresh","label":"melts into"}],"containers":[{"id":"cl-salt","nodes":["n-ocean"],"data":{"label":"Salt Water (97.5%)","formation":"radial"}},{"id":"cl-fresh","nodes":["n-fresh","n-ground","n-glacier"],"data":{"label":"Fresh Water (2.5%)","formation":"radial"}}]}`,
].join('\n');

export default function App() {
  return (
    <VisualliRenderer
      visualliString={WATER_CYCLE_JSONL}
      useWorker={true}
      theme="light"
      width="100vw"
      height="100vh"
      onNodeClick={(node) => console.log('node clicked:', node.title)}
      onLayerChange={(id, layer) => console.log('layer changed:', layer.description ?? id)}
    />
  );
}
