/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for a single line in a .visualli (JSONL) file. Each line must be one of: Meta, Extension, or Layer.
 */
export type VisualliSpec011 = Meta | Extension | Layer;

export interface Meta {
  type: "meta";
  /**
   * Visualli spec version (e.g. '0.1')
   */
  version: string;
  title: string;
  created?: string;
  lastModified?: string;
}
export interface Extension {
  type: "extension";
  /**
   * Unique identifier for the extension (e.g., 'semantic-anchors')
   */
  id: string;
  /**
   * Data payload for the extension
   */
  data?: unknown[];
  [k: string]: unknown;
}
export interface Layer {
  type: "layer";
  /**
   * UUID of the layer
   */
  id: string;
  /**
   * Hierarchy level (0 is root)
   */
  level: number;
  /**
   * UUID of the parent layer
   */
  parentLayerId?: string;
  /**
   * UUID of the specific node in the parent layer this layer attaches to
   */
  parentNodeId?: string;
  nodes?: Node[];
  connections?: Connection[];
  containers?: Container[];
  [k: string]: unknown;
}
export interface Node {
  id: string;
  position: {
    x: number;
    y: number;
    [k: string]: unknown;
  };
  data: {
    /**
     * Label text for the node
     */
    label: string;
    /**
     * A short description or summary of the node content
     */
    summary: string;
    color?: string;
  };
  [k: string]: unknown;
}
export interface Connection {
  id: string;
  /**
   * Source Node ID
   */
  from: string;
  /**
   * Target Node ID
   */
  to: string;
  data: {
    label: string;
    style?: "dashed" | "solid";
  };
  [k: string]: unknown;
}
export interface Container {
  id: string;
  /**
   * List of Node IDs contained in this group
   */
  nodes: string[];
  data: {
    /**
     * Container Label
     */
    label: string;
    /**
     * Visual arrangement of nodes within the container
     */
    formation?: "natural" | "linear" | "circular" | "tree";
    /**
     * Visual style of the container border
     */
    style?: "dashed" | "none";
  };
  [k: string]: unknown;
}
